export const REDUCER_CLEAN_REQUEST = "REDUCER_CLEAN_REQUEST";

export const FETCH_BRAND_LIST = "FETCH_BRAND_LIST";
export const FETCH_BRAND_LIST_SUCCESS = "FETCH_BRAND_LIST_SUCCESS";
export const FETCH_BRAND_LIST_FAILURE = "FETCH_BRAND_LIST_FAILURE";
export const FETCH_BRAND_BY_ID = "FETCH_BRAND_BY_ID";
export const FETCH_BRAND_BY_ID_SUCCESS = "FETCH_BRAND_BY_ID_SUCCESS";
export const FETCH_BRAND_BY_ID_FAILURE = "FETCH_BRAND_BY_ID_FAILURE";

export const FETCH_CATEGORY_LIST = "FETCH_CATEGORY_LIST";
export const FETCH_CATEGORY_LIST_SUCCESS = "FETCH_CATEGORY_LIST_SUCCESS";
export const FETCH_CATEGORY_LIST_FAILURE = "FETCH_CATEGORY_LIST_FAILURE";
export const FETCH_CATEGORY_BY_ID = "FETCH_CATEGORY_BY_ID";
export const FETCH_CATEGORY_BY_ID_SUCCESS = "FETCH_CATEGORY_BY_ID_SUCCESS";
export const FETCH_CATEGORY_BY_ID_FAILURE = "FETCH_CATEGORY_BY_ID_FAILURE";
export const FETCH_SUB_CATEGORY_LIST = "FETCH_SUB_CATEGORY_LIST";
export const FETCH_SUB_CATEGORY_LIST_SUCCESS =
  "FETCH_SUB_CATEGORY_LIST_SUCCESS";
export const FETCH_SUB_CATEGORY_LIST_FAILURE =
  "FETCH_SUB_CATEGORY_LIST_FAILURE";

export const FETCH_ATTRIBUTE_LIST = "FETCH_ATTRIBUTE_LIST";
export const FETCH_ATTRIBUTE_LIST_SUCCESS = "FETCH_ATTRIBUTE_LIST_SUCCESS";
export const FETCH_ATTRIBUTE_LIST_FAILURE = "FETCH_ATTRIBUTE_LIST_FAILURE";
export const FETCH_ATTRIBUTE_BY_ID = "FETCH_ATTRIBUTE_BY_ID";
export const FETCH_ATTRIBUTE_BY_ID_SUCCESS = "FETCH_ATTRIBUTE_BY_ID_SUCCESS";
export const FETCH_ATTRIBUTE_BY_ID_FAILURE = "FETCH_ATTRIBUTE_BY_ID_FAILURE";

export const FETCH_PRODUCT_LIST = "FETCH_PRODUCT_LIST";
export const FETCH_PRODUCT_LIST_SUCCESS = "FETCH_PRODUCT_LIST_SUCCESS";
export const FETCH_PRODUCT_LIST_FAILURE = "FETCH_PRODUCT_LIST_FAILURE";
export const FETCH_PRODUCT_BY_ID = "FETCH_PRODUCT_BY_ID";
export const FETCH_PRODUCT_BY_ID_SUCCESS = "FETCH_PRODUCT_BY_ID_SUCCESS";
export const FETCH_PRODUCT_BY_ID_FAILURE = "FETCH_PRODUCT_BY_ID_FAILURE";

export const FETCH_STORE_LIST = "FETCH_STORE_LIST";
export const FETCH_STORE_LIST_SUCCESS = "FETCH_STORE_LIST_SUCCESS";
export const FETCH_STORE_LIST_FAILURE = "FETCH_STORE_LIST_FAILURE";
export const FETCH_STORE_BY_ID = "FETCH_STORE_BY_ID";
export const FETCH_STORE_BY_ID_SUCCESS = "FETCH_STORE_BY_ID_SUCCESS";
export const FETCH_STORE_BY_ID_FAILURE = "FETCH_STORE_BY_ID_FAILURE";

export const FETCH_GROUP_LIST = "FETCH_GROUP_LIST";
export const FETCH_GROUP_LIST_SUCCESS = "FETCH_GROUP_LIST_SUCCESS";
export const FETCH_GROUP_LIST_FAILURE = "FETCH_GROUP_LIST_FAILURE";
export const FETCH_GROUP_BY_ID = "FETCH_GROUP_BY_ID";
export const FETCH_GROUP_BY_ID_SUCCESS = "FETCH_GROUP_BY_ID_SUCCESS";
export const FETCH_GROUP_BY_ID_FAILURE = "FETCH_GROUP_BY_ID_FAILURE";

export const FETCH_ROLE_LIST = "FETCH_ROLE_LIST";
export const FETCH_ROLE_LIST_SUCCESS = "FETCH_ROLE_LIST_SUCCESS";
export const FETCH_ROLE_LIST_FAILURE = "FETCH_ROLE_LIST_FAILURE";
export const FETCH_ROLE_BY_ID = "FETCH_ROLE_BY_ID";
export const FETCH_ROLE_BY_ID_SUCCESS = "FETCH_ROLE_BY_ID_SUCCESS";
export const FETCH_ROLE_BY_ID_FAILURE = "FETCH_ROLE_BY_ID_FAILURE";
